name: iamnayr
description: Code examples, tutorial and ideas
markdown: redcarpet
pygments: true
permalink: /:categories/:title
url: http://www.iamnayr.com
exclude: ["config","tmp", "log", ".rvmrc", "config.ru", "unicorn.rb", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
